[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "Continental Assist"
authors = [{name = "Continental Assist", email = "egalvan@continentalassist.com"}]
dynamic = ["version", "description"]
